// serialize.ts — turns a Post into the EXACT markdown block generate_csvs.py parses.
// This is the highest-risk code in the app; it is guarded by lintPost() (throws on any
// error-severity violation) AND proven by the golden-file + round-trip tests.

import { SECTION_HEADINGS, MAX_X_COMMENTS } from './contract';
import { lintPost, errorsOnly, type LintViolation } from './lint';
import type { Post } from './types';

export class SerializeError extends Error {
  violations: LintViolation[];
  constructor(violations: LintViolation[]) {
    super(`Cannot export: ${violations.length} blocking issue(s) must be fixed first.`);
    this.name = 'SerializeError';
    this.violations = violations;
  }
}

const oneLine = (s: string) => s.replace(/[\r\n]+/g, ' ').trim();

/** Comments must be contiguous from 1, dense, capped at 10 (parser breaks at first gap). */
function densifyComments(comments: string[]): string[] {
  return comments.map((c) => c.trim()).filter(Boolean).slice(0, MAX_X_COMMENTS);
}

/** Serialize a single post to its `## Post N:` block (no trailing separator). */
export function serialize(post: Post): string {
  const errs = errorsOnly(lintPost(post));
  if (errs.length) throw new SerializeError(errs);

  const c = post.content;
  const parts: string[] = [`## Post ${post.postNumber}: ${oneLine(post.title)}`];

  const ig = c.igFbThreads.body.trim();
  if (ig) {
    let section = `### ${SECTION_HEADINGS.igFbThreads}\n${ig}`;
    const link = c.igFbThreads.link?.trim();
    if (link) section += `\n\n**Link**: ${link}`;
    parts.push(section);
  }

  const li = c.linkedin.body.trim();
  if (li) parts.push(`### ${SECTION_HEADINGS.linkedin}\n${li}`);

  const xMain = c.x.main.trim();
  if (xMain) {
    const lines = [`### ${SECTION_HEADINGS.x}`, `**Main post**: ${xMain}`];
    densifyComments(c.x.comments).forEach((cm, i) => {
      lines.push(`\n**comment${i + 1}**: ${cm}`);
    });
    parts.push(lines.join('\n'));
  }

  const bs = c.bluesky.body.trim();
  if (bs) parts.push(`### ${SECTION_HEADINGS.bluesky}\n${bs}`);

  if (parts.length === 1) throw new SerializeError([]); // nothing but a header

  return parts.join('\n\n') + '\n';
}

/** Serialize many posts into a full converted_posts.md-style document. */
export function serializeAll(posts: Post[], title = 'PsiAN Social Media — Batch 3'): string {
  const header = `# ${title}\n\nGenerated by Cassie's PSIAN app. Ready for generate_csvs.py.\n\n---\n\n`;
  return header + posts.map(serialize).join('\n---\n\n');
}
